name: Semgrep Security Scan and DefectDojo Import

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Run Semgrep and Import to DefectDojo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep and export results
        run: |
          semgrep --config=p/ci --json -o semgrep-findings.json

      - name: Upload Semgrep findings to DefectDojo
        env:
          DOJO_URL: ${{ secrets.DOJO_URL }}
          DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
        run: |
          curl -s -S -X POST "${DOJO_URL}/api/v2/import-scan/" \
            -H "Authorization: Token ${DOJO_TOKEN}" \
            -F scan_type="Semgrep JSON Report" \
            -F file=@semgrep-findings.json \
            -F product_name="MapYourWorld Fork" \
            -F engagement_name="Semgrep Auto Scan" \
            -F auto_create_context=true \
            -F close_old_findings=true \
            -F deduplication_on_engagement=true
